### ISSUE TITLE
Question about Cognos CMS, please

### ISSUE THREAD

**Issue by xumes** [ljerka/hello-world#2]
Hello ljerka,

Sorry contact you through here, but I saw you asked a question to a developer who created a lib to access Cognos Mashup Service from Node.js.
I would really appreciate if you contact me and allow me to ask my question in a private mode (by e-mail for instance).
Please, my contact information is in my profile.

Thanks for your attention,
Reginaldo

**Comment by ljerka** [comment]
Closing since it is not really an issue...
